main:
    steps:
    - extract_and_load:
        parallel:
            branches:
            - properties:
                steps:
                - extract_opa_properties:
                    call: http.post
                    args:
                        url: https://us-central1-musa509s23-team1-philly-cama.cloudfunctions.net/extract-properties
                        auth:
                            type: OIDC
                - prepare_opa_properties:
                    call: http.post
                    args:
                        url: https://us-central1-musa509s23-team1-philly-cama.cloudfunctions.net/prepare-properties
                        auth:
                            type: OIDC
                - load_opa_properties:
                    call: http.post
                    args:
                        url: https://us-central1-musa509s23-team1-philly-cama.cloudfunctions.net/load-properties
                        auth:
                            type: OIDC
            - assessments:
                steps:
                    - extract_opa_assessments:
                        call: http.post
                        args:
                            url: https://us-central1-musa509s23-team1-philly-cama.cloudfunctions.net/extract-opa-assessments
                            auth:
                                type: OIDC
                    - prepare_opa_assessments:
                        call: http.post
                        args:
                            url: https://us-central1-musa509s23-team1-philly-cama.cloudfunctions.net/prepare-opa-assessments
                            auth:
                                type: OIDC
                    - load_opa_assessments:
                        call: http.post
                        args:
                            url: https://us-central1-musa509s23-team1-philly-cama.cloudfunctions.net/load-opa-assessments
                            auth:
                                type: OIDC
    - transform:
        parallel:
            branches:
            - current_assessments:
                steps:
                - train_model: {}
                - transform_current_assessment_bins: {}
            - tax_year_assessments:
                steps:
                - transform_tax_year_assessment_bins: {}
    - generate_site_data:
        parallel:
            branches:
            - chart_configs:
                steps:
                - generate_assessment_chart_configs: {}
            - map_tiles:
                steps:
                - generate_property_map_tiles: {}
