---
title: "data_sci_2"
author: "Avani"
date: "2024-03-27"
output: html_document
---
This markdown files consists of the first exploratory analysis of the Philadelphia
Property Tax Assessment data. We begin by setting up the required environment.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
library(car)
library(lubridate)
library(arcpullr)
library(sfdep)
library(randomForest)
library(caret)
p_load(tidyverse, sf, corrr, corrplot)
options(scipen = 999)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```
## Reading File
With our environment set up, we are now going to read the data.
```{r cars}
opa <- read.csv("opa_properties_public.csv")
opa_sf <- st_read("opa_properties_public.geojson")
glimpse(opa)

hoods <- get_spatial_layer('https://services1.arcgis.com/a6oRSxEw6eIY5Zfb/ArcGIS/rest/services/Philadelphia_Neighborhoods/FeatureServer/0')

districts <- get_spatial_layer('https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/Planning_Districts/FeatureServer/0/') %>% st_make_valid()

unique(opa$category_code_description)
unique(opa$fuel)
table(opa$category_code_description)

#filter out unneeded and redundant variables
# opa_test <- opa_sf %>%
#   select (-parcel_number, -category_code, -objectid, - house_number, - house_extension,
#           - pin, - street_code, - zip_code, - geographic_ward, - census_tract,
#           - exempt_land, - exempt_building, - market_value, - taxable_building,
#           - taxable_land)

opa_test <- opa_sf %>%
  select(category_code, census_tract, depth, fireplaces, frontage,
         garage_spaces, mailing_zip, number_of_bathrooms, number_of_rooms, sale_date,
         sale_price, total_livable_area, year_built, location, parcel_number, owner_1)

#filter by date and sale price
opa_test$timestamp <- ymd_hms(opa_test$sale_date)
#opa_test <- opa_test %>% drop_na(sale_price)
opa_test <- opa_test %>%
  filter(year(timestamp) > 2021, year(timestamp) < 2025, sale_price > 100,
         category_code == '1 ', !is.na(sale_price))

opa_test <- opa_test[opa_test$sale_price < quantile(opa_test$sale_price,prob=1-5/100),]

opa_test <- opa_test %>%
  distinct(location, owner_1, sale_price, .keep_all = TRUE)

#price lag
opa_test <- opa_test %>%
          mutate(nb = st_knn(geometry, k = 5),
                 wt = st_weights(nb),
                 price_lag = st_lag(sale_price, nb, wt))

#filter bundles, residential

#join with neighborhoods
opa_hoods <- st_join(opa_test, districts)

cor_matrix_1 <- opa_test %>%
  select_if(is.numeric)%>%
  cor(use = "complete.obs")

cor_matrix_1%>%
  correlate() %>%
  autoplot() +
  geom_text(aes(label = round(r,digits=2)),size = 2)

corrplot(cor_matrix_1, method = "circle")

opa_hoods <- opa_hoods %>%
  select(fireplaces, sale_price, garage_spaces, number_of_bathrooms, 
         total_livable_area, price_lag, ABBREV)%>%
  mutate(fireplaces = if_else(is.na(fireplaces), median(fireplaces, na.rm = TRUE), 
                              fireplaces))%>%
  mutate(garage_spaces = if_else(is.na(garage_spaces), median(garage_spaces, na.rm = 
                                                                TRUE), garage_spaces))%>%
  mutate(number_of_bathrooms = if_else(is.na(number_of_bathrooms), 
                                       median(number_of_bathrooms, na.rm = TRUE), 
                                       number_of_bathrooms))%>%
  mutate(total_livable_area = if_else(is.na(total_livable_area), 
                                      median(total_livable_area, na.rm = TRUE), 
                                      total_livable_area))

opa_clean <- opa_hoods %>%
  select(sale_price, fireplaces, garage_spaces, number_of_bathrooms, total_livable_area, 
         price_lag, ABBREV)

#random forest
opa_hoods$ABBREV <- as.factor(opa_hoods$ABBREV)
opa_clean <- model.matrix(~ ABBREV - 1, opa_hoods) %>% as.data.frame()
opa_clean <- cbind(st_drop_geometry(opa_hoods), st_drop_geometry(opa_clean))

rf1 <- randomForest(sale_price ~ ., data = 
                      opa_clean%>%st_drop_geometry()%>%select(-ABBREV))
summary(rf1$rsq)

#opa_test <- opa_test %>%
#  select_if(is.numeric)

reg.1 <- lm(sale_price ~ ., data = opa_test)
summary(reg.1)
vif(reg.1)

reg.2 <- lm(sale_price ~ ., data = opa_clean%>%st_drop_geometry())
summary(reg.2)
vif(reg.2)
```
```{r cross_validation, message=FALSE, results='hide'}

fitControl <- trainControl(method = "cv", number = 100)
set.seed(825)

reg.cv <- 
  train(sale_price ~ ., data = st_drop_geometry(opa_clean) %>% 
                                dplyr::select(sale_price, fireplaces, garage_spaces, 
                                              number_of_bathrooms, total_livable_area, 
                                              price_lag, DIST_NAME), 
     method = "lm", trControl = fitControl, na.action = na.pass)

ggplot(reg.cv$resample, aes(x=MAE)) +
  geom_histogram(fill = "#FA7800", color = "white") +
  labs(
    title = "Distribution of MAE Across 100-Fold Cross Validation",
    subtitle = "",
    caption = "Figure 10")
```
